### ISSUE TITLE
Lua errors

### ISSUE THREAD

**Issue by drum84** [icheatatlan/ClassicBestiary#2]
Hey, I'm getting constant Lua errors. Could you look into it, if you find the time? Thank you very much <3

```lua
18x Interface\AddOns\ClassicBestiary\ClassicBestiary-1.0.3.lua:14: Usage: UnitGUID("unit")
[string "=[C]"]: in function `UnitGUID'
[string "@Interface\AddOns\ClassicBestiary\ClassicBestiary-1.0.3.lua"]:14: in function <Interface\AddOns\ClassicBestiary\ClassicBestiary.lua:12>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
(*temporary) = nil

```

**Comment by icheatatlan** [comment]
I have seen this come up rarely for some people, but never frequently. Do you use some other addons that also modify the tooltip in some way?

I am releasing a big update soon that should fix this properly, but before then you can edit [ClassicBestiary.lua](https://github.com/icheatatlan/ClassicBestiary/blob/1eaaa228c6345c0cc21ab920ac4854e0e5d471b6/ClassicBestiary.lua#L13):

Replace this:
https://github.com/icheatatlan/ClassicBestiary/blob/1eaaa228c6345c0cc21ab920ac4854e0e5d471b6/ClassicBestiary.lua#L13-L16
With:
```lua
local guid = UnitGUID("mouseover")
local npc_id = guid and tonumber(({strsplit("-", guid)})[6])
if not npc_id then
  return
end
```

**Comment by drum84** [comment]
Been playing for some time now. These 4 lines fixed it, I guess. Thanks a lot! <3

Not quite sure how many of my addons interfere with the tooltip, but the known ones would be:

Bagnon
Leatrix Plus
Questie
TipTac Reborn
Vendor Price

I get all my addon through the Curse client. All of them updated daily. No Alpha/Beta builds.
