### ISSUE TITLE
Getting Errors after nearly every mob

### ISSUE THREAD

**Issue by SinisterMatti** [icheatatlan/ClassicBestiary#4]
Message: Interface\AddOns\ClassicBestiary\ClassicBestiary.lua:14: Usage: UnitGUID("unit")
Time: Thu May 18 01:46:31 2023
Count: 5
Stack: Interface\AddOns\ClassicBestiary\ClassicBestiary.lua:14: Usage: UnitGUID("unit")
[string "=[C]"]: in function `UnitGUID'
[string "@Interface\AddOns\ClassicBestiary\ClassicBestiary.lua"]:14: in function <Interface\AddOns\ClassicBestiary\ClassicBestiary.lua:12>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals: (*temporary) = nil

**Comment by icheatatlan** [comment]
Yeah, this has been popping up more frequently for people and was obviously broken in hindsight. I just published version 1.0.4 which fixes this. Thanks!
